language: ruby
notifications:
rvm:
  - 1.9.3
  bundler_args: --without integration development
  script:
    - bundle exec foodcritic -f any . --tags ~FC007 --tags ~FC015 --tags ~FC023
    - bundle exec rubocop
    - bundle exec rspec --color --format progress
